### ISSUE TITLE
`--no-discordant` seems to have no effect

### ISSUE THREAD

**Issue by bgruening** [infphilo/hisat#13]
I was running hisat  with  --no-discordant and this is the flagstat result:
```
21157717 + 0 in total (QC-passed reads + QC-failed reads)
1901341 + 0 secondary
0 + 0 supplementary
0 + 0 duplicates
20695605 + 0 mapped (97.82%:-nan%)
19256376 + 0 paired in sequencing
9628188 + 0 read1
9628188 + 0 read2
18425156 + 0 properly paired (95.68%:-nan%)
18671428 + 0 with itself and mate mapped
122836 + 0 singletons (0.64%:-nan%)
183350 + 0 with mate mapped to a different chr
139450 + 0 with mate mapped to a different chr (mapQ>=5)
```

It seems that it has no effect.
Additional information:
`/usr/local/tools/hisat/0.1.6/iuc/package_hisat_0_1_6/e1f428b67305/bin/hisat-align-s version 0.1.6-beta 64-bit Built on igm3 Fri Apr 17 13:41:58 EDT 2015 Compiler: gcc version 4.5.4 (GCC) Options: -O3 -m64 -msse2 -funroll-loops -g3 -DPOPCNT_CAPABILITY Sizeof {int, long, long long, void*, size_t, off_t}: {4, 8, 8, 8, 8, 8} `

**Comment by infphilo** [comment]
This HISAT's behavior is exactly the same as Bowtie2 (v2.2.6) - there is a slight difference.  By default, discordantly aligned pairs are linked using the 9th column (TLEN - observed Template LENgth in the SAM specification), and this field is filled with zero when using --no-discordant option.  Perhaps, you may have meant to use --no-mixed, instead of --no-discordant?
