### ISSUE TITLE
A new problem about extract_splice_sites.py

### ISSUE THREAD

**Issue by tiramisutes** [infphilo/hisat#6]
I updated the HISAT to 0.1.6-beta  and also updated that script of extract_splice_sites.py,but a  new big problem when i run the extract_splice_sites.py
This is my command and error in linux:
![1](https://cloud.githubusercontent.com/assets/10768210/7330484/f11e57be-eb21-11e4-864e-ea73798128d8.png)
The same command i can run successfully in HISAT 0.1.5-beta.

**Comment by rltillett** [comment]
tiramisutes,
I was encountering the same error and problem on my CentOS 6 server, but not on my Desktop. I beleive the issue to be tied to Python version features. My CentOS 6 machine was running python 2.6.x, and the "collection import Counter" function doesn't exist in py versions until 2.7.
-My workaround was simply to process my GTF file on my Mac (w/python 2.7.4) and transfer the splicesites.txt to my centos machine, rather than risking breaking everything by mucking up my python versions.
-Hisat devs ought to add python 2.7 as a requirement, like drop it in the README.md.

**Comment by tiramisutes** [comment]
Your explanation is very valuable,but python version is really a headache problem. Currently, the best solution is transfer the script and gtf file to the desktop.Thakns for your suggestion.

**Comment by infphilo** [comment]
As of now, I recommend using Python 2.7 or higher.
